<script lang="ts">
	/**
	 * Certificate of Completion — a print-only page appended after the document
	 * (DocuSign-style). Hidden on screen; shown only when printing / saving as PDF.
	 *
	 * It renders each signer's name, email, custom fields, signed timestamp, and —
	 * for the document owner — IP + approximate location, plus the SHA-256 the
	 * signatures are bound to. The signature is never in the document body (that
	 * would change the hash), so this certificate is where the full trail lives.
	 */
	import { onMount } from 'svelte';

	type SignField = { label: string; required: boolean };
	type SignStateSigner = {
		name: string;
		email: string;
		index: number;
		signed: boolean;
		signedAt: number | null;
		open?: boolean;
		fields?: Record<string, string> | null;
	};
	type SignState = {
		enabled: boolean;
		fields: SignField[];
		signers: SignStateSigner[];
		complete: boolean;
	};
	type AuditEvent = {
		action: string;
		signerEmail: string | null;
		contentHash: string | null;
		createdAt: string | number | null;
		ipAddress: string | null;
		location: string | null;
	};

	let {
		apiUrl,
		noteId,
		title,
		initialState
	}: { apiUrl: string; noteId: string; title: string; initialState: SignState } = $props();

	let signState = $state<SignState>(initialState);
	let events = $state<AuditEvent[]>([]);
	let isOwner = $state(false);

	// The hash the signatures bind to (from any signed/request event).
	const contentHash = $derived(events.find((e) => e.contentHash)?.contentHash || null);

	// Owner-only IP/location, keyed by signer email (from the 'signed' events).
	const metaByEmail = $derived.by(() => {
		const m = new Map<string, { ip: string | null; location: string | null }>();
		for (const e of events) {
			if (e.action === 'signed' && e.signerEmail) {
				m.set(e.signerEmail.toLowerCase(), { ip: e.ipAddress, location: e.location });
			}
		}
		return m;
	});

	function fmt(ts: number | null): string {
		if (!ts) return '—';
		try {
			return new Date(ts).toLocaleString(undefined, {
				year: 'numeric',
				month: 'long',
				day: 'numeric',
				hour: '2-digit',
				minute: '2-digit'
			});
		} catch {
			return '—';
		}
	}

	onMount(async () => {
		// Refresh state + pull the audit trail (IP/location included if owner).
		try {
			const [sRes, aRes] = await Promise.all([
				fetch(`${apiUrl}/notes/${noteId}/sign`),
				fetch(`${apiUrl}/notes/${noteId}/sign/audit`)
			]);
			if (sRes.ok) {
				const s = await sRes.json();
				if (s?.enabled) signState = s;
			}
			if (aRes.ok) {
				const a = await aRes.json();
				events = a.events || [];
				isOwner = !!a.isOwner;
			}
		} catch {
			/* certificate degrades gracefully to what we already have */
		}
	});
</script>

<!-- Print-only: this whole block is display:none on screen. -->
<section class="mdpubs-certificate">
	<h2>Certificate of Completion</h2>
	<p class="cert-doc">Document: <strong>{title}</strong></p>
	{#if contentHash}
		<p class="cert-hash">Document hash (SHA-256): <span>{contentHash}</span></p>
	{/if}
	<p class="cert-status">
		Status: {signState.complete ? 'Completed — all parties signed' : 'In progress'}
	</p>

	<table class="cert-table">
		<thead>
			<tr>
				<th>Signer</th>
				<th>Signed</th>
				{#if isOwner}<th>IP / Location</th>{/if}
			</tr>
		</thead>
		<tbody>
			{#each signState.signers as s (s.index)}
				{@const meta = metaByEmail.get((s.email || '').toLowerCase())}
				<tr>
					<td>
						<div class="cert-name">{s.name}</div>
						{#if s.email}<div class="cert-sub">{s.email}</div>{/if}
						{#if s.fields}
							{#each Object.entries(s.fields) as [k, v] (k)}
								<div class="cert-sub">{k}: {v}</div>
							{/each}
						{/if}
					</td>
					<td>{s.signed ? fmt(s.signedAt) : 'Not signed'}</td>
					{#if isOwner}
						<td class="cert-sub">
							{meta?.ip || '—'}{#if meta?.location}<br />{meta.location}{/if}
						</td>
					{/if}
				</tr>
			{/each}
		</tbody>
	</table>

	<p class="cert-foot">
		Generated by MdPubs · This certificate records the signatures bound to the document hash above.
		Any change to the document after signing invalidates these signatures.
	</p>
</section>

<style>
	/* Hidden on screen; only materializes for print / save-as-PDF. */
	.mdpubs-certificate {
		display: none;
	}
	@media print {
		.mdpubs-certificate {
			display: block;
			break-before: page;
			padding: 2rem 0;
			font-family:
				ui-sans-serif,
				system-ui,
				sans-serif;
			color: #111;
		}
		.mdpubs-certificate h2 {
			font-size: 1.25rem;
			font-weight: 700;
			margin-bottom: 0.75rem;
			border-bottom: 2px solid #111;
			padding-bottom: 0.35rem;
		}
		.mdpubs-certificate .cert-doc,
		.mdpubs-certificate .cert-status {
			font-size: 0.85rem;
			margin: 0.15rem 0;
		}
		.mdpubs-certificate .cert-hash {
			font-size: 0.7rem;
			font-family: ui-monospace, monospace;
			word-break: break-all;
			color: #444;
			margin: 0.35rem 0 0.75rem;
		}
		.cert-table {
			width: 100%;
			border-collapse: collapse;
			margin-top: 0.5rem;
			font-size: 0.8rem;
		}
		.cert-table th,
		.cert-table td {
			border: 1px solid #999;
			padding: 0.4rem 0.55rem;
			text-align: left;
			vertical-align: top;
		}
		.cert-table th {
			background: #f0f0f0;
			font-weight: 600;
		}
		.cert-name {
			font-weight: 600;
		}
		.cert-sub {
			font-size: 0.72rem;
			color: #555;
		}
		.cert-foot {
			margin-top: 1rem;
			font-size: 0.68rem;
			color: #666;
		}
	}
</style>
